class MainView:
    def menu_principal(self):
        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
        print("--BIENVENUE SUR LE GESTIONNAIRE DE TOURNOIS D'ECHECS--")
        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
        print("------------------  MENU PRINCIPAL  ------------------")
        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
        print("1 --> Pour accéder au menu des joueurs")
        print("2 --> Pour accéder au menu des tournoi")
        print("3 --> Pour accéder au menu des rapports")
        print("0 --> Pour Quitter")
        print("")
        return input("Votre choix: ")
