# Players
ADD_PLAYER = "1"
DISPLAY_PLAYERS = "2"
DISPLAY_PLAYER_BY_INE = "3"

# Tournament
CREATE_TOURNAMENT = "1"
DISPLAY_TOURNAMENTS = "2"
START_NEW_TOURNAMENT = "3"
RESUME_TOURNAMENT = "4"

# Report
DISPLAY_TOURNAMENT_LIST = "1"
DISPLAY_PLAYERS_LIST = "2"
DISPLAY_TOURNAMENT_NAME_DATES = "3"
DISPLAY_TOURNAMENT_LIST_PLAYER = "4"
DISPLAY_TOURNAMENT_NUMBER_OF_ROUND = "5"
DISPLAY_TOURNAMENT_LIST_OF_MATCHS = "6"
